# Generated by Django 2.2.6 on 2019-11-03 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_place_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('title', models.CharField(max_length=200, verbose_name='Имя')),
                ('image', models.ImageField(upload_to=utils.upload.unique_path, verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('note', models.TextField(verbose_name='Заметки (запреты, советы)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.Place', verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('RESERVED', 'RESERVED'), ('CANCELED', 'CANCELED'), ('APPROVED', 'APPROVED')], default='RESERVED', max_length=100, verbose_name='Статус заказа')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('a6b1576a-9b73-4b7c-b784-b6eb434abe71'), unique=True, verbose_name='Билет')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
