# Generated by Django 2.2.6 on 2019-11-03 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5e6297d9-5d2c-4db9-ac45-1e6d48047562'), unique=True, verbose_name='Билет'),
        ),
    ]
