# Generated by Django 2.2.6 on 2019-11-03 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191103_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('77e3d7d3-7dba-432d-bf72-b607faaf562a'), unique=True, verbose_name='Номер билета'),
        ),
    ]
