# Generated by Django 2.2.6 on 2019-11-03 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191103_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Время мероприятий'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e48ade11-2760-484c-8128-9e21a64a5bcc'), unique=True, verbose_name='Номер билета'),
        ),
    ]
