# Generated by Django 2.2.6 on 2019-11-03 10:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191103_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fd4a7006-b17e-466a-8938-a62cab5701c8'), unique=True, verbose_name='Номер билета'),
        ),
    ]
