# Generated by Django 2.2.6 on 2019-11-03 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191103_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('79c272fc-c2bc-426e-b974-68e29beaf55f'), unique=True, verbose_name='Номер билета'),
        ),
    ]
