# Generated by Django 2.2.6 on 2019-11-03 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20191103_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5b7b3d30-09d8-46ea-acf2-db4c6cee2a20'), unique=True, verbose_name='Номер билета'),
        ),
    ]
