# Generated by Django 2.2.6 on 2019-11-10 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191103_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6589081a-46f1-4621-a6a2-fea4fc65d1ab'), unique=True, verbose_name='Номер билета'),
        ),
    ]
