# Generated by Django 2.2.6 on 2019-11-10 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20191110_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b7d24cc1-a7ac-4602-9b19-b8f6ceb6cbdf'), unique=True, verbose_name='Номер билета'),
        ),
    ]
