# Generated by Django 2.2.6 on 2019-11-10 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191110_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4398f17a-784a-4fa1-bcda-9390e33ccc8c'), unique=True, verbose_name='Номер билета'),
        ),
    ]
