# Generated by Django 2.2.6 on 2019-11-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191103_1732'),
        ('shop', '0011_auto_20191110_1414'),
    ]

    operations = [
    ]
