# Generated by Django 2.2.6 on 2019-11-10 09:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_merge_20191110_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('67be1450-3020-494e-ae6c-825f637226f3'), unique=True, verbose_name='Номер билета'),
        ),
    ]
