# Generated by Django 2.2.6 on 2019-11-10 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20191110_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bd44dbd8-eafd-4315-93f7-d030da57f567'), unique=True, verbose_name='Номер билета'),
        ),
    ]
