# Generated by Django 2.2.6 on 2019-12-02 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20191110_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1e00e6d3-7118-4ee0-9e74-b720c5e6e532'), unique=True, verbose_name='Номер билета'),
        ),
    ]
