# Generated by Django 2.2.6 on 2020-05-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20191204_2246'),
        ('shop', '0017_auto_20191207_1225'),
    ]

    operations = [
    ]
