# Generated by Django 2.2.6 on 2021-02-19 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20191204_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('96ecfe2f-fc77-4d21-88ef-20edf7d65d55'), unique=True, verbose_name='Номер билета'),
        ),
    ]
