# Generated by Django 2.2.6 on 2021-02-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210219_1253'),
        ('shop', '0019_merge_20200502_1112'),
    ]

    operations = [
    ]
