# Generated by Django 2.2.6 on 2021-02-22 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20210222_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(default='Gi', max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ff605790-9b4b-4f95-b9fe-90a82bfe0ecf'), unique=True, verbose_name='Номер билета'),
        ),
    ]
