# Generated by Django 2.2.6 on 2021-02-22 08:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210222_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('274b7947-bd7a-4a56-b91a-7b5a634ed3d8'), unique=True, verbose_name='Номер билета'),
        ),
    ]
