# Generated by Django 2.2.6 on 2021-02-22 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20210222_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6fa428f9-9de3-4a07-b728-937d230fa631'), unique=True, verbose_name='Номер билета'),
        ),
    ]
