OK = 0
BAD_REQUEST = 1
EMAIL_NOT_CONFIRMED_ERROR = 2
INCORRECT_PIN = 3
PIN_LIMIT = 4
SAME_FACE_PIN = 5
FACE_PAY_DISABLED = 6
IMAGE_USED = 7
NO_CARD = 8

UNAUTHORIZED = 401
TOKEN_EXPIRED = 9
TOKEN_REFRESH_EXPIRED = 10

SERVER_ERROR = 999
