ACTIVATION_TIME = 10
SEARCH_SIMILARITY = 0.3

FEEDBACK_PENDING = 'pending'
FEEDBACK_APPROVED = 'approved'
FEEDBACK_DECLINED = 'declined'

FEEDBACK_STATUSES = (
    (FEEDBACK_PENDING, FEEDBACK_PENDING),
    (FEEDBACK_APPROVED, FEEDBACK_APPROVED),
    (FEEDBACK_DECLINED, FEEDBACK_DECLINED),
)
