ACTIVATION_TIME = 10
SEARCH_SIMILARITY = 0.3

FEEDBACK_PENDING = 'pending'
FEEDBACK_APPROVED = 'approved'
FEEDBACK_DECLINED = 'declined'

FEEDBACK_STATUSES = (
    (FEEDBACK_PENDING, FEEDBACK_PENDING),
    (FEEDBACK_APPROVED, FEEDBACK_APPROVED),
    (FEEDBACK_DECLINED, FEEDBACK_DECLINED),
)

CREATED = 'CREATED'
SUCCESS = 'SUCCESS'
FAILURE = 'FAILURE'
REFUND = 'REFUND'

PAYMENT_STATUSES = (
    (CREATED, CREATED),
    (SUCCESS, SUCCESS),
    (FAILURE, FAILURE),
    (REFUND, REFUND)
)

RESERVED = 'RESERVED'
CANCELED = 'CANCELED'
APPROVED = 'APPROVED'

ORDER_STATUSES = (
    (RESERVED, RESERVED),
    (CANCELED, CANCELED),
    (APPROVED, APPROVED)
)

MAX_FILE_SIZE = 2 * 1024 * 1024
