# Generated by Django 2.2.6 on 2019-11-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_auto_20191103_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('meta_text', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('get_text', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('CHECK', 'CHECK'), ('RESULT', 'RESULT'), ('REFUND', 'REFUND'), ('CAPTURE', 'CAPTURE'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE')], default='RESULT', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('total_price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=100)),
                ('card_pan', models.CharField(blank=True, max_length=100, null=True)),
                ('refund_callback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REFUND', 'REFUND')], db_index=True, default='CREATED', max_length=10)),
                ('pg_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_testing_mode', models.SmallIntegerField(default=1)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-id'],
            },
        ),
    ]
