# Generated by Django 2.2.6 on 2019-11-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191103_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallBack',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='card_pan',
            new_name='card',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pg_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pg_testing_mode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refund_callback',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_price',
        ),
    ]
