# Generated by Django 2.2.6 on 2019-11-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20191110_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
