# Generated by Django 2.2.6 on 2019-10-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
