# Generated by Django 2.2.6 on 2019-10-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='PlaceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Название заведения')),
                ('avatar_url', models.ImageField(max_length=1000, upload_to='images/')),
                ('rating', models.FloatField(default=0.0, null=True, verbose_name='Рейтинг заведения')),
                ('review_count', models.IntegerField(default=0, verbose_name='Количество голосов')),
                ('description', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Описание заведения')),
                ('address', models.CharField(max_length=10000, null=True, verbose_name='Адрес заведения')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phones', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Телефоны заведения')),
                ('website_url', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Ссылка на сайт')),
                ('working_hours', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Часы работы')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='core.City', verbose_name='Город заведения')),
                ('place_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='core.PlaceType', verbose_name='Тип заведения')),
                ('services', models.ManyToManyField(blank=True, related_name='places', to='core.PlaceService')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведения',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='core.Country', verbose_name='Страна'),
        ),
    ]
