# Generated by Django 2.2.6 on 2019-10-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_place_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='country',
        ),
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена посещений'),
        ),
    ]
