# Generated by Django 2.2.6 on 2019-10-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191006_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('-rating',), 'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведения'},
        ),
    ]
