# Generated by Django 2.2.6 on 2019-11-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_placeuserrating_placeuserratingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='price',
        ),
    ]
