# Generated by Django 2.2.6 on 2019-11-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_place_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='avatar_url',
            new_name='avatar',
        ),
    ]
