# Generated by Django 2.2.6 on 2019-12-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191110_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
    ]
